// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcZiFX3afiO7QZElEzOQcLQEz3VBWqVQ',
    appId: '1:778867565516:web:cf07d24d6e439de9ea7369',
    messagingSenderId: '778867565516',
    projectId: 'cover-app-16a88',
    authDomain: 'cover-app-16a88.firebaseapp.com',
    storageBucket: 'cover-app-16a88.firebasestorage.app',
    measurementId: 'G-88E65615N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmS31VeIPSYswJRg0uEz_ShHmovpzKFR8',
    appId: '1:778867565516:android:b724f9fbf56b234bea7369',
    messagingSenderId: '778867565516',
    projectId: 'cover-app-16a88',
    storageBucket: 'cover-app-16a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr49hpuEKQhgofuR8-X5C4rfVb35-X194',
    appId: '1:778867565516:ios:e81b0c52ac3186e6ea7369',
    messagingSenderId: '778867565516',
    projectId: 'cover-app-16a88',
    storageBucket: 'cover-app-16a88.firebasestorage.app',
    iosBundleId: 'com.isaac.shiftCover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr49hpuEKQhgofuR8-X5C4rfVb35-X194',
    appId: '1:778867565516:ios:d7c45813867fe46fea7369',
    messagingSenderId: '778867565516',
    projectId: 'cover-app-16a88',
    storageBucket: 'cover-app-16a88.firebasestorage.app',
    iosBundleId: 'com.example.shiftCover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVcZiFX3afiO7QZElEzOQcLQEz3VBWqVQ',
    appId: '1:778867565516:web:2b2979f73dbf99b7ea7369',
    messagingSenderId: '778867565516',
    projectId: 'cover-app-16a88',
    authDomain: 'cover-app-16a88.firebaseapp.com',
    storageBucket: 'cover-app-16a88.firebasestorage.app',
    measurementId: 'G-0EY8MWGW5Z',
  );
}
